version: "3.9"

services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=django
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    ports:
      - "8111:8000"
    volumes:
      - "./app:/code"
  #  command: python manage.py migrate
  #  entrypoint: ./docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - MYSQL_USER=django
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=password
    depends_on:
      - db
    links:
      - "db:db"


  adminer:
    image: adminer
    ports:
      - "8112:8080"
    links:
      - "db:db"
    depends_on:
      - db
