# Generated by Django 3.2.14 on 2022-07-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_massage_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='address',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='bot',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='photo',
        ),
    ]
