# Generated by Django 3.2.14 on 2022-07-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20220719_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotList',
            new_name='BotCommand',
        ),
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
